apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-standard
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
